<?xml version="1.0"?>
<package format="3">
  <name>enimia_black_description</name>
  <version>3.0.0</version>
  <description>Modele URDF du prototype ENIMIA Black Edition (ENIM Team Tunisia - Shell Eco-marathon)</description>
  <maintainer email="team@enim.tn">ENIM Team Tunisia</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
