cmake_minimum_required(VERSION 3.8)
project(localization)
find_package(ament_cmake REQUIRED)
foreach(directory config launch urdf)
  if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${directory}")
    install(DIRECTORY "${directory}" DESTINATION share/${PROJECT_NAME})
  endif()
endforeach()
install(PROGRAMS scripts/imu_stamper.py
  DESTINATION lib/${PROJECT_NAME})
ament_package()
