<?xml version="1.0"?>
<package format="3">
  <name>dashboard_bridge</name>
  <version>0.0.1</version>
  <description>Simulation telemetry bridge for the e-ink dashboard.</description>
  <maintainer email="ahmed@example.com">Ahmed</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <exec_depend>python3-pil</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
